### ISSUE TITLE
ISS Writing issue

### ISSUE THREAD

**Issue by lanops** [zeropingheroes/lanager#60]
File writing permission problems on ISS requesting access to folders outside the "Storage" worth updating the documentation to note ISS is slightly more picky. 

ErrorException (E_UNKNOWN) 
Directory C:\inetpub\Lanager\vendor\ezyang\htmlpurifier\library/HTMLPurifier/DefinitionCache/Serializer not writable, please alter file permissions (View: C:\inetpub\Lanager\app\views\shouts\partials\list.blade.php) (View: C:\inetpub\Lanager\app\views\shouts\partials\list.blade.php

Added write to this particular folder - seemed to fix our issue. 

IIS - Php 5.6 mysql 5.6.21

**Comment by mt-inside** [comment]
I see this on Apache/Unix as well, and have to run the following (lanager is installed into / because this is a container):
chmod -R 0777 /lanager/app/storage
chmod -R 0777 /lanager/vendor/ezyang/htmlpurifier/library/HTMLPurifier/DefinitionCache/Serializer

The x bit might not be necessary, but this gets it running.

**Comment by ilumos** [comment]
This is now fixed as of 3fd4c386cb61ac045da64302f776f15ac061f530
