### ISSUE TITLE
Dashboard View Suggestions

### ISSUE THREAD

**Issue by azjose** [zeropingheroes/lanager#76]
Would be nice to have 2 or 3 columns that would have like Games Played, Events and Shouts.

Also would be nice to have new shouts append to the top of the shout list. New shouts are added to bottom right now and no one can seem on dashboard view on the projector. Also shouts don't seem to be pinning either.

**Comment by ilumos** [comment]
Yes the current layout gets quite crowded when there's lots going on.

I think rather than squashing everything into a 3-column layout, a possible solution would be to fade between games, events and shouts every 15 seconds or so. What do you reckon?

Re the wrong sort order for shouts, that'll get fixed once I've finished refactoring some backend code

**Comment by x-zempt** [comment]
With the Dashboard view, it would also be handy to have the names of the players listed of who is in game instead of just the display pic, and maybe have the name clickable to their profile. 
Once again, love you work!

**Comment by ilumos** [comment]
The dashboard is intended to be displayed on a big screen and viewed from a distance so space is limited, so I won't be adding usernames or links there, sorry.

You can get the same information for who's in which game, with profile links by going to the "games" page

**Comment by x-zempt** [comment]
Yea that makes sense.

**Comment by ilumos** [comment]
I've put shouts and games in progress into a carousel in 41fd1c91653a4bdf6770c35eeb3fc46360c5fd2e (dev branch) making better use of the space available.
